apiVersion: v1
kind: ConfigMap
metadata:
 name: prometheus-config
 namespace: yb-demo
data:
 prometheus.yml: |
  global:
  scrape_configs:
   - job_name: 'kubernetes-kubelet'
     scheme: https
     tls_config:
       ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
       insecure_skip_verify: true
     bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
     kubernetes_sd_configs:
     - role: node
     relabel_configs:
     - action: labelmap
       regex: __meta_kubernetes_node_label_(.+)
     - target_label: __address__
       replacement: kubernetes.default.svc.cluster.local:443
     - source_labels: [__meta_kubernetes_node_name]
       regex: (.+)
       target_label: __metrics_path__
       replacement: /api/v1/nodes/${1}/proxy/metrics
   - job_name: 'kubernetes-cadvisor'
     scheme: https
     tls_config:
       ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
       insecure_skip_verify: true
     bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
     kubernetes_sd_configs:
     - role: node
     relabel_configs:
     - action: labelmap
       regex: __meta_kubernetes_node_label_(.+)
     - target_label: __address__
       replacement: kubernetes.default.svc.cluster.local:443
     - source_labels: [__meta_kubernetes_node_name]
       regex: (.+)
       target_label: __metrics_path__
       replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
   - job_name: 'kubernetes-kube-state'
     kubernetes_sd_configs:
     - role: pod
     relabel_configs:
     - action: labelmap
       regex: __meta_kubernetes_pod_label_(.+)
     - source_labels: [__meta_kubernetes_namespace]
       action: replace
       target_label: kubernetes_namespace
     - source_labels: [__meta_kubernetes_pod_name]
       action: replace
       target_label: kubernetes_pod_name
     - source_labels: [__meta_kubernetes_pod_label_grafanak8sapp]
       regex: .*true.*
       action: keep
     - source_labels: ['__meta_kubernetes_pod_label_daemon', '__meta_kubernetes_pod_node_name']
       regex: 'node-exporter;(.*)'
       action: replace
       target_label: nodename
   - job_name: 'yugabytedb'
     metrics_path: /prometheus-metrics
     static_configs:
      - targets: ['yb-master-0.yb-masters.yb-demo.svc.cluster.local:7000', 'yb-master-1.yb-masters.yb-demo.svc.cluster.local:7000', 'yb-master-2.yb-masters.yb-demo.svc.cluster.local:7000']
        labels:
          group: 'yb-master'

      - targets: ['yb-tserver-0.yb-tservers.yb-demo.svc.cluster.local:9000', 'yb-tserver-1.yb-tservers.yb-demo.svc.cluster.local:9000', 'yb-tserver-2.yb-tservers.yb-demo.svc.cluster.local:9000']
        labels:
          group: 'yb-tserver'

      - targets: ['yb-tserver-0.yb-tservers.yb-demo.svc.cluster.local:11000', 'yb-tserver-1.yb-tservers.yb-demo.svc.cluster.local:11000', 'yb-tserver-2.yb-tservers.yb-demo.svc.cluster.local:11000']
        labels:
          group: 'yedis'

      - targets: ['yb-tserver-0.yb-tservers.yb-demo.svc.cluster.local:12000', 'yb-tserver-1.yb-tservers.yb-demo.svc.cluster.local:12000', 'yb-tserver-2.yb-tservers.yb-demo.svc.cluster.local:12000']
        labels:
          group: 'ycql'

      - targets: ['yb-tserver-0.yb-tservers.yb-demo.svc.cluster.local:13000', 'yb-tserver-1.yb-tservers.yb-demo.svc.cluster.local:13000', 'yb-tserver-2.yb-tservers.yb-demo.svc.cluster.local:13000']
        labels:
          group: 'ysql'
   - job_name: 'istio-mesh'
     scrape_interval: 5s
     kubernetes_sd_configs:
     - role: endpoints
       namespaces:
         names:
         - istio-system
     relabel_configs:
     - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
       action: keep
       regex: istio-telemetry;prometheus
   - job_name: 'envy'
     scrape_interval: 5s
     kubernetes_sd_configs:
     - role: endpoints
       namespaces:
         names:
         - istio-system
     relabel_configs:
     - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
       action: keep
       regex: istio-statsd-prom-bridge;statsd-prom
   - job_name: 'istio-policy'
     scrape_interval: 5s
     kubernetes_sd_configs:
     - role: endpoints
       namespaces:
         names:
         - istio-system
     relabel_configs:
     - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
       action: keep
       regex: istio-policy;http-monitoring
   - job_name: 'istio-telemetry'
     scrape_interval: 5s
     kubernetes_sd_configs:
     - role: endpoints
       namespaces:
         names:
         - istio-system
     relabel_configs:
     - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
       action: keep
       regex: istio-telemetry;http-monitoring
   - job_name: 'pilot'
     scrape_interval: 5s
     kubernetes_sd_configs:
     - role: endpoints
       namespaces:
         names:
         - istio-system
     relabel_configs:
     - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
       action: keep
       regex: istio-pilot;http-monitoring
   - job_name: 'galley'
     scrape_interval: 5s
     kubernetes_sd_configs:
     - role: endpoints
       namespaces:
         names:
         - istio-system
     relabel_configs:
     - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
       action: keep
       regex: istio-galley;http-monitoring